config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups, path: 'categories', only: [:new, :index, :create] do
    resources :records, only: [:new, :index, :create]
  end
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    can :manage, Group, user_id: user.id
    can :manage, Record, user_id: user.id
    can :manage, :all if user.role == 'admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end
return

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true
  validates_uniqueness_of :name, scope: :user_id

  has_many :records, foreign_key: 'group_id'
  belongs_to :user

  def total_amount
    total = 0
    records.each do |record|
      total += record.amount
    end
    total
  end
end
return

app/models/record.rb
class Record < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :amount, presence: true

  belongs_to :group
  belongs_to :user
end
return

app/models/user.rb
class User < ApplicationRecord
  has_many :groups, foreign_key: 'user_id'
  has_many :records, foreign_key: 'user_id'
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def destroy
    @group = Group.find(params[:id])
    @records = @group.records
    @records.destroy_all
    @group.destroy
    redirect_to groups_path, notice: 'Group deleted.'
  end

  def index
    @groups = Group.all.order(created_at: :desc).limit(100)
  end

  def new
    @group = Group.new
    @icons_url = [
      'icons/01.jpg', 'icons/02.jpg', 'icons/03.jpg', 'icons/04.jpg', 'icons/05.jpg',
      'icons/06.jpg', 'icons/07.jpg', 'icons/08.jpg', 'icons/09.jpg', 'icons/10.jpg',
      'icons/11.jpg', 'icons/12.jpg', 'icons/13.jpg', 'icons/14.jpg', 'icons/15.jpg',
      'icons/16.jpg', 'icons/17.jpg', 'icons/18.jpg', 'icons/19.jpg', 'icons/20.jpg',
      'icons/21.jpg', 'icons/22.jpg', 'icons/23.jpg', 'icons/24.jpg', 'icons/25.jpg'
    ]
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      flash[:notice] = 'Group created!'
      redirect_to groups_path
    else
      flash[:notice] = @group.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.json do
        @users = User.all
        render json: @users, only: [:name], status: :ok
      end
      format.html
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to group_records_path(params[:group_id]), notice: 'Record deleted.'
  end

  def index
    @group = Group.find(params[:group_id])
    @records = @group.records.order(created_at: :desc).limit(100)
  end

  def new
    @record = Record.new
    @group = Group.find(params[:group_id])
    @groups = Group.where(user_id: current_user)
  end

  def create
    if record_groups_id.nil?
      flash[:notice] = 'Select a group'
      redirect_to request.referrer
    else
      record_groups_id.each do |group_id|
        @record = Record.new(record_params)
        @record.user = current_user
        @record.group = Group.find(group_id)
        flash[:notice] = 'Record created!'
        unless @record.save
          flash[:notice] = @record.errors.full_messages.join(', ')
          return redirect_to request.referrer
        end
      end
      redirect_to group_records_path(params[:group_id])
    end
  end

  private

  def record_params
    params.require(:record).permit(:name, :amount)
  end

  def record_groups_id
    params.require(:record)['group']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end
return

app/helpers/groups_helper.rb
module GroupsHelper
end
return

app/helpers/home_helper.rb
module HomeHelper
end
return

app/helpers/records_helper.rb
module RecordsHelper
end
return

app/views/groups/index.html.erb
<div class="container">
  <header>
    <%= link_to root_path, class:"back-link" do %>
      <%= image_tag 'back-arrow.svg', alt: '🡠', class: "back-img" %>
    <% end %>
    <h2>CATEGORIES</h2>
    <span class="next-link"></span>
  </header>
  <div class="cards-container">
    <div class="cards">
      <% @groups.each do |group|%>
        <% if can? :read, group %>
          <%= link_to group_records_path(group) do%>
            <div class="group-card">
              <%= image_tag (group.icon || 'icons/01.jpg'), alt: group.icon, class: "img-icon" %>
              <span class="card-name"><%= group.name %></span>
              <span class="amount">$ <%= group.total_amount %></span>
            </div>
          <% end %>
          <% if current_user.role == 'admin' %>
            <p> Created by <%= group.user.name %> </p>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="btn-container">
      <%= link_to "Create Category", new_group_path, class:"create-btn" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<%= form_with model: @group, url: groups_path  do |f| %>
  <div class="container">
    <header>
      <%= link_to groups_path, class:"back-link" do %>
        <%= image_tag 'back-arrow.svg', alt: '🡠', class: "back-img" %>
      <% end %>
      <h2>NEW CATEGORY</h2>
      <%= f.submit "Next", class: 'next-link' %>
    </header>
    <div class="form-container">
      <div class="field">
        <%= f.text_field :name, placeholder: 'Category name', class: 'input-field' %>
      </div>
      <div class="dash"></div>
      <div class="icons-field">
        <% @icons_url.each do |icon| %>
          <label>
            <%= f.radio_button :icon, icon, class: 'radio-input'%>
            <%= image_tag icon, alt: icon, class: "img-icon" %>
          </label>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="splash-screen-container">
  <div class="logo-container">
    <h1>Budget Manager</h1>
  </div>
  <nav>
    <% unless user_signed_in? %>
      <%= link_to "Sign In", new_user_session_path, class:"top-link"%>
      <%= link_to "Sign Up", new_user_registration_path, class:"bt-link"%>
    <% else %>
      <%= link_to "Categories", groups_path, class:"top-link"%>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete}, class:"bt-link"%>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<div class="container">
  <header>
    <%= link_to groups_path, class:"back-link" do %>
      <%= image_tag 'back-arrow.svg', alt: '🡠', class: "back-img" %>
    <% end %>
    <h2>Transactions</h2>
    <span class="next-link"></span>
  </header>
  <div class="group-info">
    <%= image_tag (@group.icon || 'icons/01.jpg'), alt: @group.icon, class: "img-icon" %>
    <span class="group-info-name"><%= @group.name%></span>
    <span class="amount">$ <%= @group.total_amount%></span>
  </div>
  <div class="cards-container">
    <div class="cards">
      <% @records.each do |record|%>
        <div class="record-card">
          <span class="card-name" > Record: <%= record.name %></span>
          <span class="amount"> $ <%= record.amount %></span>
        </div>
      <% end %>
    </div>
    <div class="btn-container">
      <%= link_to "Create Transaction", new_group_record_path(params[:group_id]), class:"create-btn" %>
    </div>
  </div>
</div>

app/views/records/new.html.erb
<%= form_with model: @record, url: group_records_path(@group) do |f| %>
  <div class="container">
    <header>
      <%= link_to group_records_path(params[:group_id]), class:"back-link" do %>
        <%= image_tag 'back-arrow.svg', alt: '🡠', class: "back-img" %>
      <% end %>
      <h2>New Transaction</h2>
      <%= f.submit "Next", class: 'next-link' %>
    </header>
    <div class="form-container">
      <div class="field">
        <%= f.text_field :name, placeholder: 'Transaction name', class: 'input-field' %>
      </div>
      <div class="dash"></div>
      <div class="field">
        <%= f.number_field :amount, step: 0.01, placeholder: 'Transaction Amount', class: 'input-field' %>
      </div>
      <div class="dash"></div>
      <div class="groups-selection">
        <% @groups.each do |group| %>
          <label>
            <div class="group-card">
              <%= f.check_box :group, { multiple: true,  checked: group == @group }, group.id, nil%>
              <%= image_tag (group.icon || 'icons/01.jpg'), alt: group.icon, class: "img-icon" %>
              <span class="card-name"><%= group.name %></span>
            </div>
          </label>
        <% end %>
      </div>
    </div>
  </div>
<% end %>